FROM apache/airflow:2.9.3-python3.12
USER root
RUN mkdir -p /opt/airflow/.local && chown -R airflow:airflow /opt/airflow
USER airflow
COPY requirements-airflow.txt /opt/airflow/requirements.txt
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt
