services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: analytics
      POSTGRES_PASSWORD: analytics
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    env_file: .env
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__RBAC: "true"
      _PIP_ADDITIONAL_REQUIREMENTS: ""
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./src:/opt/airflow/src
      - ./dbt:/opt/dbt
      - ./.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: bash -lc "airflow db init && airflow users create --username airflow --password airflow --firstname Air --lastname Flow --role Admin --email admin@example.com || true && airflow webserver & airflow scheduler"
    depends_on:
      - postgres

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.3
    env_file: .env
    environment:
      DBT_PROFILES_DIR: /opt/dbt/profiles
    volumes:
      - ./dbt:/opt/dbt
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase:latest
    ports: ["3000:3000"]
    depends_on:
      - postgres

volumes:
  pgdata:
