job_cost_adjusted:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: analytics
      password: analytics
      port: 5432
      dbname: warehouse
      schema: public
